// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHnaz5F2Czm513vwgsL5LL7-lvnghlmBY',
    appId: '1:315244188799:web:e57fcff83b641821a1db4a',
    messagingSenderId: '315244188799',
    projectId: 'memomusicplayer',
    authDomain: 'memomusicplayer.firebaseapp.com',
    storageBucket: 'memomusicplayer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeaR33aHIrbdnJXn1xWskBuUezLwwBYlg',
    appId: '1:315244188799:android:55f76347a22a979aa1db4a',
    messagingSenderId: '315244188799',
    projectId: 'memomusicplayer',
    storageBucket: 'memomusicplayer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa2xePk0YGMpNbsGA2KXI_ib3Gq7mnN5A',
    appId: '1:315244188799:ios:af980b1caa8d9a36a1db4a',
    messagingSenderId: '315244188799',
    projectId: 'memomusicplayer',
    storageBucket: 'memomusicplayer.appspot.com',
    iosClientId: '315244188799-kfjrgal16hvqnu4qvpqc7t94qq0s527k.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa2xePk0YGMpNbsGA2KXI_ib3Gq7mnN5A',
    appId: '1:315244188799:ios:ff9d699cfc33c25ba1db4a',
    messagingSenderId: '315244188799',
    projectId: 'memomusicplayer',
    storageBucket: 'memomusicplayer.appspot.com',
    iosClientId: '315244188799-5qrfqm66o0rjccgu2ai111lj08go3702.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicplayer.RunnerTests',
  );
}
